### ISSUE TITLE
ReferenceError: Calendar is not defined

### ISSUE THREAD

**Issue by haiGodzilla** [panaghia/google-meet-link-apple-cal#1]
hello there, dunno if this project is still alive but wanted to try anyway. 
I followed the steps you described und while running the script I ran into:
```
ReferenceError: Calendar is not defined
    at checkForNewEvents(Code:13:18)
```
Tried to specify the calendar with the ID instead of 'primary'. Still same result.
Any ideas?

**Comment by panaghia** [comment]
Hey @haiGodzilla, easy fix:
in Google Script project, click on "Services" → Add "Google Calendar API"

Remember: to test it, you should create a calendar event with no conference link and with at least one guest.

Hope it helps!
